### ISSUE TITLE
Add commit badge

### ISSUE THREAD

**Issue by arshadkazmi42** [arshadkazmi42/ak-phrase.js#42]
```
[![Commit](https://img.shields.io/github/last-commit/arshadkazmi42/ak-phrase.js.svg)](https://github.com/arshadkazmi42/ak-phrase.js/commits/master)
```
adds commit badge

**Comment by mridulguptaa** [comment]
i wanna work on this.

**Comment by arshadkazmi42** [comment]
@mridulguptaa These are first timers only issue, for helping new contributors getting started.
So we would want 1 contributor per first-timers issue.

**Comment by AbdelrahmanManz** [comment]
@arshadkazmi42 Can I claim this?

**Comment by arshadkazmi42** [comment]
@MubbyGN yes. Its yours. Go ahead create a PR
