### ISSUE TITLE
Add npm version badge

### ISSUE THREAD

**Issue by arshadkazmi42** [arshadkazmi42/ak-phrase.js#43]
```
[![NPM Version](https://img.shields.io/npm/v/ak-phrase.svg)](https://www.npmjs.com/package/ak-phrase)
```

Add above line in readme.md with other badges

**Comment by mridulguptaa** [comment]
i want to work on this. May i proceed if no one is working upon this?

**Comment by arshadkazmi42** [comment]
Go ahead

**Comment by arshadkazmi42** [comment]
@mridulguptaa Any updates on this?

**Comment by abigailmunsen** [comment]
If the other person doesn't, I would love to take this on.

**Comment by arshadkazmi42** [comment]
@abigailmunsen We haven't heard from @mridulguptaa 
I think you can work on it, if you want
