### ISSUE TITLE
Add license badge

### ISSUE THREAD

**Issue by arshadkazmi42** [arshadkazmi42/ak-phrase.js#48]
`[![LICENSE](https://img.shields.io/npm/l/ak-phrase.svg)](https://github.com/arshadkazmi42/ak-phrase.js/LICENSE)`

add above line in README.md with other badges

**Comment by marielenna** [comment]
Can I work on this?

**Comment by arshadkazmi42** [comment]
@marieram This is first timers only issue, these issues are for beginners who want to create their first PR. Seems like you have already done some contributions to this Repo.
Let's keep this open for some other contributors who want to create their first PR

**Comment by jtertil** [comment]
Hey, I'm ready to work on it. This will be my first-time commit.

**Comment by arshadkazmi42** [comment]
@jtertil Cool. go ahead
