### ISSUE TITLE
update package name in readme

### ISSUE THREAD

**Issue by cdrani** [arshadkazmi42/ak-phrase.js#54]
The readme labels the wrong package name. The package name is `ak-phrase` not `ak-phrase.js`. You can check by running:
`npm info ak-phrase.js` vs `npm info ak-phrase`.

```diff
- $ npm install ak-phrasae.js
+ $ npm install ak-phrase
```

and 

```diff
- const sentenceGenerator = require('ak-phrase.js');
+ const sentenceGenerator = require('ak-phrase');
```

This might also be a good chance to update the repo name to reflect the npm package name. Updating the docs count as a patch update:  1.0.3 -> 1.0.4

**Comment by arshadkazmi42** [comment]
Really good catch. Thank you for reporting.
Would you like to send a PR with the changes?

**Comment by cdrani** [comment]
Sure. Update everything including the readme h1? I'll leave it up to you whether you want to release a patch version or wait.

**Comment by arshadkazmi42** [comment]
We are planning for a release, there are some more changes in the README.
I will be adding issues for those.
We will push a new release with all the changes together.

**Comment by cdrani** [comment]
Ok. Will send PR shortly.
