### ISSUE TITLE
is generateSentencePermutations supposed to be exposed?

### ISSUE THREAD

**Issue by cdrani** [arshadkazmi42/ak-phrase.js#55]
Noticed that `generateSentences` is not exported by default. `generateSentencePermutations` is already incorporated into `generateSentences`, thus I don't know if users are going to use it, especially as it is not documented in the readme. If there's no reason for users to use `generateSentencePermutations` function, then `generateSentences` can be the sole function exported by default. This would also require a change to the readme in how `generateSentences` is imported.

**Comment by arshadkazmi42** [comment]
Actually that makes sense, there is no need of exporting `generateSentencePermutations`.
I had plan of changing it, but it got off my mind.
I think it need not be exported, I don't see any usecase for users that anyone will be using that function directly.
If you would like to send a PR for this I would be happy to get it reviewed and merged.

**Comment by cdrani** [comment]
Sure.
