### ISSUE TITLE
replace npm with yarn in CONTRIBUTING.md

### ISSUE THREAD

**Issue by cdrani** [arshadkazmi42/ak-phrase.js#56]
> Run below command to verify all tests are passing
npm install (This will install all required dependencies)
npm test

I suppose this is meant to use `yarn` from the `yarn.lock` file.

**Comment by arshadkazmi42** [comment]
actually it supports both, I was using yarn while building it and while setting up the repository, I think I used npm everywhere. We can centralize it to use either npm or yarn and accordingly update `yarn.lock` or `package-lock.json` file

**Comment by cdrani** [comment]
I know it supports both, but the consensus, I believe, is to develop using only one.
> We highly recommend you to delete the package-lock.json file if you decide to use yarn in order to avoid future confusion and possible consistency issues.


https://yarnpkg.com/blog/2018/06/04/yarn-import-package-lock/

**Comment by arshadkazmi42** [comment]
True. We should not use npm and yarn both, it can make the maintenance of the library difficult

**Comment by cdrani** [comment]
PR incoming.
