### ISSUE TITLE
obese npm package

### ISSUE THREAD

**Issue by cdrani** [arshadkazmi42/ak-phrase.js#59]
The packages includes every single file/folder in the repo. Packages should be as lightweight as possible. In this case, the only files that should be packed and sent to npm registry is the index.js, license, readme, and package.json.
In package.json add:
```js
"files": ["index.js"]
```
The other 3 files will be automatically packed by npm.

**Comment by arshadkazmi42** [comment]
Sounds reasonable. We should surely do this.
I am also planning on adding .eslint config added a issue for it #60

**Comment by cdrani** [comment]
I will send a PR for this quite soon.
