### ISSUE TITLE
add eslint

### ISSUE THREAD

**Issue by arshadkazmi42** [arshadkazmi42/ak-phrase.js#60]
We need to add eslint config to standardise the coding style

**Comment by cdrani** [comment]
Yes. I was just thinking this. In addition to eslint, prettier would also be good.

**Comment by arshadkazmi42** [comment]
I have not used prettier before, if you want you can add it too.
I have an eslint config which I use in most of my JS project [here](https://github.com/arshadkazmi42/awesome-github-init/tree/master/configs/linter/nodejs)
